---
- name: Build and Push Docker Image to Docker Hub
  hosts: localhost  # Set the target to the control machine
  gather_facts: false  # No need to gather facts on the control machine
  vars:
    docker_image_name: your_dockerhub_username/your_image_name
    docker_image_tag: latest
    git_repo_url: https://github.com/yourusername/yourrepo.git

  tasks:
    - name: Clone Git repository on the control machine
      git:
        repo: "{{ git_repo_url }}"
        dest: /tmp/yourrepo

    - name: Build Docker image on the control machine
      docker_image:
        path: /tmp/yourrepo
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: build

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ container_registry_credential.username }}"
        password: "{{ container_registry_credential.password }}"
        email: "{{ container_registry_credential.email }}"

    - name: Push Docker image to Docker Hub
      docker_image_push:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"

    - name: Log out from Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        state: absent
