---
- name: Build and Push Docker Image to Docker Hub
  hosts: all
  become: true
  become_user: root
  vars:
    docker_image_name: ayoubelmimouni/test-ansible
    docker_image_tag: latest
    git_repo_url: https://github.com/digitalocean/sample-dockerfile.git

  tasks:
    - name: Clone Git repository on the control machine
      git:
        repo: "{{ git_repo_url }}"
        dest: /tmp/yourrepo

    - name: Build Docker image on the control machine
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: build
        build:
          path: /tmp/yourrepo

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_basic_username }}"
        password: "{{ docker_basic_password }}"

    - name: Push Docker image to Docker Hub
      community.docker.docker_image:
        push: true
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"

    - name: Log out from Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        state: absent
