---
- name: Build and Push Docker Image to Docker Hub
  hosts: all
  become: true
  become_user: root
  vars:
    docker_image_name: ayoubelmimouni/test-ansible
    docker_image_tag: latest
    git_repo_url: https://github.com/digitalocean/sample-dockerfile.git

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: /tmp/yourrepo

    - name: Build Docker image
      docker_image:
        path: /tmp/yourrepo
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: build

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ container_registry_credential.username }}"
        password: "{{ container_registry_credential.password }}"

    - name: Push Docker image to Docker Hub
      docker_image_push:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"

    - name: Log out from Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        state: absent
