---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: false


  vars:
    instance_type: "m4.2xlarge"
    image_id: "ami-06873c81b882339ac"
    key_name: "main_kp"
    region: "ca-central-1"
    security_group: "sg-022b83a9e56b7ff53"
    subnet_id: "subnet-0497d4a4b815f3750"

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "ansible-AWX-instance"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 100
              delete_on_termination: true
        vpc_subnet_id: "{{ subnet_id }}"
        network:
          assign_public_ip: true
        wait: true
        tags:
          Environment: Testing
        state: "{{ state | default('absent') }}"

      register: ec2_instance

    - name: Print EC2 instance details
      debug:
        var: ec2_instance
      when: state == 'started'
      
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: just_launched
      loop: "{{ ec2_instance.instances }}"
      when: state == 'started'


- hosts: just_launched
  become: true
  become_user: root
  
  vars:
    docker_image_name: ayoubelmimouni/test-ansible
    docker_username: '{{ docker_basic_username }}'
    docker_password: '{{ docker_basic_password }}'
    github_username: '{{ github_basic_username }}'
    github_password: '{{ github_basic_password }}'
    repo_name: digital-twin
    org_name: Bio-Twin
  tasks:
    # Install Docker on the EC2 instance
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: state == 'started'
    - name: Install Git
      apt:
        name: git
        state: present
      when: state == 'started'
    
    - name: Clone Git repository
      git:
        repo: 'https://{{ github_password }}@github.com/{{ org_name }}/{{ repo_name }}.git'
        dest: /tmp/yourrepo
      when: state == 'started'

    - name: Generate Docker image tag
      set_fact:
        docker_image_tag: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      when: state == 'started'

    - name: Show Docker image tag
      debug:
        var: docker_image_tag
      when: state == 'started'
      register: docker_build_result

    - name: Build Docker image on the control machine
      docker_image:
        name: '{{ docker_image_name }}'
        tag: '{{ docker_build_result.docker_image_tag }}'
        source: build
        state: present
        build:
          path: /tmp/yourrepo

    - name: Run Docker Container
      docker_container:
        name: my_container
        image: '{{ docker_image_name }}:{{ docker_build_result.docker_image_tag }}'
        state: started
        detach: false
        cleanup: true
        env:
          DYNACONF_MONGO_CONNECTION_STRING: '{{ MONGO_CONNECTION_STRING }}'
          DYNACONF_SLACK_WEB_HOOK_URL: '{{ SLACK_WEB_HOOK_URL }}'
          DYNACONF_DATABASE_NAME: '{{ DATABASE_NAME }}'
          DYNACONF_DATABASE_USER: '{{ DATABASE_USER }}'
          DYNACONF_DATABASE_PASSWORD: '{{ DATABASE_PASSWORD }}'
          DYNACONF_DATABASE_URL: '{{ DATABASE_URL }}'
          DYNACONF_DATABASE_PORT: '{{ DATABASE_PORT }}'
          DYNACONF_SHAREPOINT_USERNAME: '{{ SHAREPOINT_USERNAME }}'
          DYNACONF_SHAREPOINT_PASSWORD: '{{ SHAREPOINT_PASSWORD }}'
          DYNACONF_AC_SHAREPOINT_URL: '{{ AC_SHAREPOINT_URL }}'
          DYNACONF_DT_SHAREPOINT_URL: '{{ DT_SHAREPOINT_URL }}'
          DYNACONF_SHAREPOINT_PROGENESIS_FOLDER: '{{ SHAREPOINT_PROGENESIS_FOLDER }}'
          DYNACONF_SHAREPOINT_EXCEL_FILE_PATH_BLOOD: '{{ SHAREPOINT_EXCEL_FILE_PATH_BLOOD }}'
          DYNACONF_SHAREPOINT_EXCEL_FILE_PATH_URINE: '{{ SHAREPOINT_EXCEL_FILE_PATH_URINE }}'
          DYNACONF_SHAREPOINT_EXCEL_FILE_PATH_SALIVA: '{{ SHAREPOINT_EXCEL_FILE_PATH_SALIVA }}'
          DYNACONF_MARIADB_USER: '{{ MARIADB_USER }}'
          DYNACONF_MARIADB_PASSWORD: '{{ MARIADB_PASSWORD }}'
          DYNACONF_MARIADB_URL: '{{ MARIADB_URL }}'
          DYNACONF_MARIADB_DATABASE_NAME: '{{ MARIADB_DATABASE_NAME }}'
          DYNACONF_CLEARML_WEB_HOST: '{{ CLEARML_WEB_HOST }}'
          DYNACONF_CLEARML_API_HOST: '{{ CLEARML_API_HOST }}'
          DYNACONF_CLEARML_FILES_HOST: '{{ CLEARML_FILES_HOST }}'
          DYNACONF_CLEARML_API_ACCESS_KEY: '{{ CLEARML_API_ACCESS_KEY }}'
          DYNACONF_CLEARML_API_SECRET_KEY: '{{ CLEARML_API_SECRET_KEY }}'
      when: state == 'started'
