---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: false


  vars:
    instance_type: "t2.micro"
    image_id: "ami-06873c81b882339ac"  # Amazon Linux 2 AMI, replace with your desired AMI
    key_name: "main_kp"
    region: "ca-central-1"
    security_group: "sg-022b83a9e56b7ff53"
    subnet_id: "subnet-0497d4a4b815f3750"
    count: 1
    docker_image_name: ayoubelmimouni/test-ansible
    git_repo_url: https://github.com/digitalocean/sample-dockerfile.git
    docker_username: '{{ docker_basic_username }}'
    docker_password: '{{ docker_basic_password }}'

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "ansible-AWX-instance"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        count: "{{ count }}"
        network:
          assign_public_ip: true
        wait: true
        tags:
          Environment: Testing
        state: "{{ state | default('absent') }}"

      register: ec2_instance

    - name: Print EC2 instance details
      debug:
        var: ec2_instance
      when: state == 'started'
      
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: just_launched
      loop: "{{ ec2_instance.instances }}"
      when: state == 'started'


- hosts: just_launched
  become: true
  become_user: root
  tasks:
    # Install Docker on the EC2 instance
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: state == 'started'
    - name: Install Git
      apt:
        name: git
        state: present
      when: state == 'started'
    
    - name: Clone Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: /tmp/yourrepo
      when: state == 'started'

    - name: Generate Docker image tag
      set_fact:
        docker_image_tag: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      when: state == 'started'

    - name: Show Docker image tag
      debug:
        var: docker_image_tag
      when: state == 'started'
      register: docker_build_result

    - name: Build Docker image
      command: "docker build -t {{ docker_image_name }}:{{ docker_build_result.docker_image_tag }} /tmp/yourrepo"
      become: true
      when: state == 'started'


    - name: Log in to Docker Hub
      command: "docker login -u {{ docker_username }} -p {{ docker_password }}"
      become: true
      when: state == 'started'

    - name: Push Docker image to Docker Hub
      command: "docker push {{ docker_image_name }}:{{ docker_build_result.docker_image_tag }}"
      become: true
      when: state == 'started'

    - name: Log out from Docker Hub
      command: "docker logout"
      become: true
      when: state == 'started'

