---
- name: Example Playbook with github creds
  hosts: all
  become: true
  become_user: root

  vars:
    github_username: '{{ github_basic_username }}'
    github_password: '{{ github_basic_password }}'
    repo_name: twin-tech-web
    org_name: Bio-Twin
  
  tasks:
    - name: Clone Git repository
      git:
        repo: 'https://{{ github_password }}@github.com/{{ org_name }}/t{{ repo_name }}.git'
        dest: /tmp/yourrepo
        
