---
- name: Build and Push Docker Image to Docker Hub
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Run Docker Container
      docker_container:
        name: my_container
        image: busybox
        command: ["sleep", "30"]
        state: started
        detach: true

      register: docker_result
      
    - name: Wait for the container to exit
      command: docker inspect -f '{{ .State.ExitCode }}' my_container
      register: exit_code_result
      until: exit_code_result.stdout != '0'
      retries: 60
      delay: 10


    - name: Pause to allow container to start
      pause:
        seconds: 5

    - name: Save status
      set_fact:
        container_is_running: "{{ docker_result.container.State.Running }}"

    - fail:
        msg: "The service is not running"
      when: not container_is_running
