---
- name: Build and Push Docker Image to Docker Hub
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Run Docker Container
      docker_container:
        name: my_container
        image: busybox
        command: ["sleep", "20"]
        state: started
        detach: true

      register: docker_result
  
    - name: Pause to allow container to start
      pause:
        seconds: 5

    - name: Save status
      set_fact:
        container_is_running: "{{ docker_result.status == 'started' }}"

    - fail:
        msg: "The service is not running"
      when: not container_is_running
