---
- name: Build and Push Docker Image to Docker Hub
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Run Docker Container
      docker_container:
        name: my_container
        image: busybox
        command: ["sleep", "30"]
        state: started
        detach: false
        cleanup: true

