---
- name: Create S3 Bucket
  hosts: localhost
  gather_facts: false

  vars:
    region: "ca-central-1"
    bucket_name: "test-awx-bucket-biotwin"
    acl: "private"  

  tasks:
    - name: Create S3 bucket
      s3_bucket:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID" }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ region }}"
        name: "{{ bucket_name }}"
        acl: "{{ acl }}"
      register: s3_bucket_result

    - name: Print S3 bucket details
      debug:
        var: s3_bucket_result
