---
- name: Example Playbook with Custom Credentials
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Example Task
      debug:
        var:
          - username_from_credential
      vars:
        username_from_credential: "{{ rest_api_token }}"
