---
- name: Example Playbook with Custom Credentials
  hosts: all
  become: true
  become_user: root

  vars:
    your_custom_credential: "{{ rest_api_token }}"

  tasks:
    - name: Build Docker image
      command: "echo {{ your_custom_credential }}"
      become: true
